### ISSUE TITLE
Sending gratitude

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/simple-footnotes#1]
I think it is only appropriate that the first issue of this new repository be used to send gratitude to @stuartlangridge for creating the Simple Footnotes plugin. Due to his contribution, Pelican users have been able to add nice-looking footnote functionality for their sites for the last five years. Thank you, Stuart! 👏

In recent weeks I have converted Simple Footnotes to the [new namespace plugin format](https://github.com/getpelican/pelican/issues/2641) and migrated it to its own repository under the new [Pelican Plugins organization](https://github.com/pelican-plugins). And as of this morning, I'm happy to announce that I just released [Simple Footnotes 1.0.0](https://github.com/pelican-plugins/simple-footnotes/releases/tag/1.0.0), which is, to the best of my knowledge, the first Pelican plugin in the new namespace format to be [published to PyPI](https://pypi.org/project/pelican-simple-footnotes/). 🎊

This is also the first project I've tested with [GitHub Actions CI](https://github.com/features/actions) and [AutoPub](https://github.com/autopub/autopub), allowing for automated package distribution publishing upon PR merge.

Once again, thanks to Stuart and the other fine folks who have contributed to Simple Footnotes! 🙇

**Comment by justinmayer** [comment]
Thanks also to @lindzey, @mattvonrocketstein, @linevych, and @johnmarkschofield for your contributions to the Simple Footnotes plugin! 🥇

**Comment by mcepl** [comment]
Could somebody explain in README how it is better than plain rST footnotes?

**Comment by stuartlangridge** [comment]
Speaking purely for myself, I use Markdown, which is why I wrote the plugin. I don't know about rST; if their footnotes also have a larger tap/click area than the footnote marker, and the footnotes link back to their marker as simple-footnotes's footnotes do, then perhaps the rST ones are fine and rST users don't need this plugin, which seems OK.

**Comment by mcepl** [comment]
https://matej.ceplovi.cz/blog/harry-potter-poznamky-jako-odpoved.html is written just with pure rST. The only plugin I have is [``zot4rst``](https://gitlab.com/egh/zot4rst) which is not relevant here.

**Comment by justinmayer** [comment]
Thank you for taking the time to elaborate, Stuart. Much appreciated.
