### ISSUE TITLE
Doesn't play nicely with render-math plugin using reStructuredText

### ISSUE THREAD

**Issue by drewhutchison** [pelican-plugins/simple-footnotes#3]
I'm reformatting my pelican content from markdown to rst and have noticed an interesting issue. To wit, my articles that rendered fine using the [pelican-render-math](https://github.com/pelican-plugins/render-math) plugin now seem not to work _only if_ they also include footnotes using this plugin. Near as I can tell, something that plugin does in course of its munging seems to get hung up on the `[ref]` or `[/ref]` tokens used here, but do seem to work if I rename these in my content and in `simple_footnotes.py:37,38,89` to something like `[foo]`.

This is definitely an odd issue and I haven't quite run it to ground, but I'd propose as a solution making the text of the delimiters configurable for the plugin while retaining a default of the current `ref` to preserve existing behavior. I should be able to construct a reproducible case as well as this change in the next day or two but wanted to open this issue to see if the maintainers agree with this course of action.

**Comment by justinmayer** [comment]
Interesting. Proposed solution is okay with me, but it might make sense to first understand *why* there is a problem with the current footnote marker.

**Comment by drewhutchison** [comment]
Yep, agree completely. I'm pretty sure the problem is somewhere deep within the layers of render-math, and I'm very far from understanding how that works. Regardless, here's steps to repro:

Start a new blog with pelican quickstart:

```
(pelicanweirdness) drew@DESKTOP-1KDPFN2:~/tmp/pelicanweirdness$ pelican-quickstart
Welcome to pelican-quickstart v4.2.0.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.


Using project associated with current virtual environment.Will save to:
/home/drew/tmp/pelicanweirdness

> What will be the title of this web site? title
> Who will be the author of this web site? author
> What will be the default language of this web site? [en]
> Do you want to specify a URL prefix? e.g., https://example.com   (Y/n) n
> Do you want to enable article pagination? (Y/n) n
> What is your time zone? [Europe/Paris]
> Do you want to generate a tasks.py/Makefile to automate generation and publishing? (Y/n)
> Do you want to upload your website using FTP? (y/N)
> Do you want to upload your website using SSH? (y/N)
> Do you want to upload your website using Dropbox? (y/N)
> Do you want to upload your website using S3? (y/N)
> Do you want to upload your website using Rackspace Cloud Files? (y/N)
> Do you want to upload your website using GitHub Pages? (y/N)
Done. Your new project is available at /home/drew/tmp/pelicanweirdness
```

Clone the plugins repo:

```
(pelicanweirdness) drew@DESKTOP-1KDPFN2:~/tmp/pelicanweirdness$ git clone https://github.com/getpelican/pelican-plugins.git plugins
Cloning into 'plugins'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 5866 (delta 10), reused 14 (delta 5), pack-reused 5814
Receiving objects: 100% (5866/5866), 3.23 MiB | 3.73 MiB/s, done.
Resolving deltas: 100% (2793/2793), done.
(pelicanweirdness) drew@DESKTOP-1KDPFN2:~/tmp/pelicanweirdness$ (cd plugins && git log -1 --format="%H")
f191788fe0bf3cae54f22b5b447dd23b8d32364e
```

Enable both plugins via the following change to `pelicanconf.py`:

```diff
37,38d36
< PLUGIN_PATHS=['./plugins']
< PLUGINS = ['simple_footnotes', 'render_math']
```

Create the following file as `content/test.rst`:

```reStructuredText
Test Post
#########

:author: author
:date: 1900-01-01

The area of a circle is :math:`A_\text{c} = (\pi/4) d^2`.

Here's my written text[ref]and here is a footnote[/ref].
```

Then `make html` and observe that, although the LaTeX _does_ get wrapped as `span.math`, the render_math plugin doesn't inject the `<script>` tag needed for mathjax to do its thing.

Interestingly, if you create the following as `content/test2.rst`

```reStructuredText
Test Post 2
###########

:author: author
:date: 1900-01-02

The area of a circle is :math:`A_\text{c} = (\pi/4) d^2`.
```

that is, without the `[ref]`s, it _does_ inject the `<script>` tag, and that successfully picks up and transforms the gibberish from the _other_ article that wasn't working before (unless you click through to that article on its own page, in which case the behavior reverts). I'm noting this not because it's particularly relevant to any possible fix but just because it might help inform investigation.

As noted above, renaming the `[ref]`s to `[foo]`s in both the article source and the three relevant lines from the footnotes plugin and everything works fine, so I'm guessing that token is used for something special somewhere amidst the (myriad) transformations that render_math does. That makes it definitely a problem more on their side than yours, and I'll try and dig in later and see if I can isolate where the disconnect is occurring. I suggested this enhancement just because 1) it's comparatively pretty easy to implement and 2) I could see a similar issue arising with other plugins or script includes, and being able to change the `[ref]` token to something that didn't conflict would be a universal workaround. But, you're right, we should figure out what's going on.

**Comment by justinmayer** [comment]
Thanks for the detailed notes. I don’t think it will make a difference, but keep in mind that both Simple Footnotes and Render Math plugins have been migrated to their own individual repos under the new Pelican Plugins organization, and yet it seems from your write-up that you are testing those two plugins from the legacy monolithic repository. The code may not have changed significantly enough to make a difference, but it’s best to be sure that the problem can be reproduced from the code that is actually current/maintained.

**Comment by drewhutchison** [comment]
On the contrary, that seems totally to have fixed it 🤦

Closing this out, sincere apologies for the waste of your time.
